### ISSUE TITLE
RES allocation to agg. LA

### ISSUE THREAD

**Issue by nesnoj** [openego/ding0#123]
Currently, LV RES are allocated randomly to all LA. Thus, RES count is proportional to LA area. This might lead to an overestimation of RES in agg. LA. In future scenarios, when RES capacity is linearly scaled according to installed capacity of status quo, this results in a massive overestimation. Hence, we might not be able to neglect LV grid losses.
In a first step, the LA-specific ratio (installed RES capacity / peak load) has to be determined to approximate LV grid losses. Related issue: #124 

To achieve a realistic RES count in agg. LA, we might limit the max. installed capacity.

In general, RES allocated to agg. LA are to be aggregated in LA object (revise [current code](https://github.com/openego/dingo/blob/a1ef0f8051ae6af59cf2edb623a470d7dba6702d/dingo/core/structure/regions.py#L104-L108)).

**Comment by piaulous** [comment]
Deprecated, new allocation method in #380.
