### ISSUE TITLE
enhance logging

### ISSUE THREAD

**Issue by nesnoj** [openego/ding0#141]
Mail from @gplssm:

Ein paar Punkte gibts noch, die man diskutieren könnte:

1) Du hast ja häufig debub print mit "if debug:" abgefragt. Jetzt habe ich sie im find&replace Rausch einfach als log mit dem Level debug versehen. Ist ganz schön Doppelmoppelkäse. Ich schlage vor das "if debug:" einfach zu entfernen. Dann werden die Debug-Nachrichten einfach ins Logfile geschrieben.
2) Die Pfeile "===>". Willst du die beibehalten? Die wirken im Konsolenlog übrigens etwas anders als im Filelog.
3) Handhabung Logfile (z.B. rotational log)
4) PyPSA printed direkt an prompt (zumindest mit gegenwärtiger Version. Ich weiß, dass sie auf ein Loggingsystem umstellen wollten)

**Comment by mltja** [comment]
Not a problem with #380
