### ISSUE TITLE
Move results tables ORM classes to ego.io

### ISSUE THREAD

**Issue by gplssm** [openego/ding0#142]
Currently, these ORM table definitions are located in [Dingo](https://github.com/openego/dingo/blob/a29a2452bcb8503c7e72a02e1df8c6f5e56e78f1/dingo/config/config_db_interfaces.py)

These should be moved to ego.io, but be aware: Once, ego.io table definitions are update (by script) based on existing DB tables, these tables definitions may get lost if tables are not available in the DB. Consider that when moving these table definitions

**Comment by piaulous** [comment]
Deprecated, now saio is used, see #380.
