### ISSUE TITLE
Deep analysis of MV topology

### ISSUE THREAD

**Issue by nesnoj** [openego/ding0#186]
Without having done statistical analyses in many MVGD the topology seems to be visually good:

```
mv_grid_districts = [3545, 3537, 3573, 3502, 3543,
                     3437, 3536, 3580, 3576, 3532,
                     3426, 3568, 3602, 3557, 3448]
```

![mvgd_multi_topo](https://cloud.githubusercontent.com/assets/15910173/26723271/ffd7551e-4793-11e7-8aa3-50f16ce0102d.png)

However, the MV topology seems - at least visually - to be odd in some MVGD.

```
mv_grid_districts = [3537]
```

![mvgd3537_topo](https://cloud.githubusercontent.com/assets/15910173/26723191/9e7464b0-4793-11e7-8e7f-5a89107695ca.png)

We have nested rings and heaps of line crossings (#11) here.
As the ring topology is determined in the routing, it might be of interest why LA can't be connected during ring construction (voltage/current violation). To get a better understanding I added a [class](https://github.com/openego/dingo/blob/feature/debug_topology/dingo/tools/debug_topo.py) to collect these reasons in branch [`feature/debug_topology`](https://github.com/openego/dingo/tree/feature/debug_topology) which is filled in [`tech_constraints_satisfied()`](https://github.com/openego/dingo/blob/feature/debug_topology/dingo/grid/mv_grid/models/models.py#L215) and results are printed in [example file](https://github.com/openego/dingo/blob/feature/debug_topology/examples/example_single_grid_district.py#L61-L63).

The violations include:
```
LA count      (try to connect more LA than allowed)
current hring (violation of current for a half ring)
voltage hring (violation of voltage for a half ring)
current ring  (violation of current for a full ring)
voltage ring  (violation of voltage for a full ring)
```

For MVGD 3537 we get
```
voltage hring  19696
voltage ring   14013
```
So restrictions are put by allowed voltage range, mainly in half rings ([threshold 5%](https://github.com/openego/dingo/blob/feature/debug_topology/dingo/config/config_calc.cfg#L126)).

Currently only visual aspects drive a more in-deep analysis, we have to re-discuss the need again as soon as the statistical analysis in #178 is finished.

**Comment by piaulous** [comment]
Closed, because mentioned in #212.
