### ISSUE TITLE
Low-voltage grid and load area statistics

### ISSUE THREAD

**Issue by gplssm** [openego/ding0#190]
1. **Create data structure for LV/LA statistics** Until now, the statistical analysis of Dingo grid data focused on MV grids. The dataframe generated by `calculate_mvgd_stats()` can only contain one line per MV grid district. Hence, data on underlying LAs and LV grids can only be stored in aggregated manner. Find a suitable data structure, maybe inspired by the MV grid stats data, to efficiently store statistics about LV grids/LA

2. **Implement following LV key figures** one number for each LV grid district
- [x] Total length on cables
- [x] Cumulative length of each cable type
- [x] Number of branches (total and for each sector)
- [x] Cumulative generation capacity
- [x] Cumulative peak load
- [x] Sectoral peak load
- [x] Generation capacity directly connected at bus bar of station
- [x] Number and cumulative nominal apparent power of transformers
- [x] Number of sectoral loads and its average peak loads
- [x] Number of branches per sector
- [x] Cumulative capacity of each generator type
- [x] Population
- [x] Branches with remaining over-voltage or line overloading issues

3. **Load area** statistics
- [x] Cumulative generation capacity
- [x] Cumulative peak load

**Comment by miguelparadacontzen** [comment]
A function is implemented in [here](https://github.com/openego/ding0/blob/features/stats-export/dingo/tools/results.py#L270).
