### ISSUE TITLE
LV grid drawing with genos fails

### ISSUE THREAD

**Issue by nesnoj** [openego/ding0#193]
GridDingo's [`graph_draw()`](https://github.com/openego/dingo/blob/5b87bdf75a70de79f89a66fe93f1ec20e39c93b1/dingo/core/network/__init__.py#L82) method fails when drawing LV grid if there're generators in the grid. It stucks [here getting genos' neighbor](https://github.com/openego/dingo/blob/5b87bdf75a70de79f89a66fe93f1ec20e39c93b1/dingo/core/network/__init__.py#L151).
If genos do not have neighbors, are they connected to grid at all? They do not seem to be any edges connecting genos :(.
Do we suffer a dp bug? Any hints on this @gplssm ?

**Comment by piaulous** [comment]
Closed, outdated due to new lv grid generation method and therefore new plotting in #380.
