### ISSUE TITLE
Issues according to tests

### ISSUE THREAD

**Issue by miguelparadacontzen** [openego/ding0#200]
While running tests in the reg-tests branch, I have found the following issues:

1. Function `to_dataframe` does not sort its outcome. So two different runs over the same network, will typically give two differently ordered outputs. A workaround is already implemented in the branch, but the sorting criteria for the lines is its `'length'` attribute.
EDIT: `to_dataframe` now gives sorted edges, and therefore all works fine. See point 2 below.

2. The IDs of the lines/branches are not unique in different runs of dingo. 
EDIT: this was because the method `graph_edges()` sorted the edges according to their representative, which was defined after the first adj_node of the branch. As the order of the adj nodes of a branch is not always the same in different runs of dingo, then each branch had two possible representatives. furthermore, every edge starting in a given node would possibly have the same representative. This was fixed by sorting the branches according to both previously sorted nodes. The implementation is already merged to dev. See [here](https://github.com/openego/ding0/blob/dev/ding0/core/network/__init__.py#L231).

3. The adjacent nodes of a branch might be inverted in different runs of dingo. Therefore, the `'geom'`attribute of the dataframe is not necessarily the same one. 
EDIT: It is still like this. For the regression tests, a workaround was done, see [here](https://github.com/openego/ding0/blob/dev/ding0/tools/tests.py#L152).

4. Different runs of dingo set the values of the `'s_res'`attributes of the branches and the `'v_res'`attributes of the nodes to different values!! Rounding them to 5 decimal places seems to solve the problem for the nodes, but not for the branches. 
EDIT: It is a rouding/precission problem. For the tests, a workaround was done, see [here](https://github.com/openego/ding0/blob/dev/ding0/tools/tests.py#L171). For the edges, the values are also rounded when saved: [here](https://github.com/openego/ding0/blob/dev/ding0/tools/pypsa_io.py#L574).

5. The most critical thing, is that, some times, two different runs of dingo give solutions with a different number of nodes! I have not testes what kind of nodes are they, but in the cases that this happens there is one extra node.

EDIT: everything is merged to dev and working fine :)

**Comment by nesnoj** [comment]
Concerning 5.:
I tried to track down but unsuccessfully until now.
The issue seems to be related to connection of MV generators in [`mv_connnect()`](https://github.com/openego/dingo/blob/7848c10197b825f8ffba39681cbb59016323ea67/dingo/grid/mv_grid/mv_connect.py#L808). To go on your can checkout the branch `features/node_finder` which contains some debugging stuff.

**Comment by nesnoj** [comment]
5. was solved in https://github.com/openego/ding0/commit/0ef1253f383482e32d76e86fa96a4bf3c40c045c, thank you @miguelparadacontzen!

What of the problems 1-4 have not been solved yet? @miguelparadacontzen
