### ISSUE TITLE
Statistical analysis of the entire Dingo dataset (on MV level)

### ISSUE THREAD

**Issue by gplssm** [openego/ding0#214]
_This is a list of possible statistical evaluation aspects provided as inspiration for @mlinsenmeier 's  seminar paper_

- Distribution of transformer size and number of transformers (HV-MV and MV-LV)
- Cumulative underground cable and overhead lines length, cumulative length for each cable/line type
- Missing MV grid districts (for some grid districts no topology could be constructed due to data artefacts)
- Cumulative load and generation per grid district
  - Distinguish total load from load within aggregated load areas
  - Generation capacity disaggregated by technology
- Correlation between
  - Nominal voltage - population density
  - Nominal voltage - length of longest line
  - Aggregated load/generation - population density
  - _feel free to extend this_
- Distribution of amount of rings
- Distribution on branche length
- Total branch lenght vs. total ring lenght
- Total number of ringnetworks, total number of outgoing lines
- Distribution of outgoing line length of each HV-MV substation for 10 and 20kV Networks
- Number of connectet MV-LV substations per ring (total and for 10 and 20kV Networks)

**Comment by jochenbuehler** [comment]
Please verify the following values (distance between stations, maximum length of outgoing lines) with the Dingo dateset: 
![unbenannt](https://user-images.githubusercontent.com/28706452/28619744-356a8d9a-720a-11e7-820d-fbd6283d9360.png)

**Comment by jochenbuehler** [comment]
Also please verify these values (source: Brunekreeft G, Luhmann T, Menz T, Muller S and Recknagel P 2015 Regulatory Pathways For Smart Grid Development in China 1st ed (Springer Vieweg)):

![1](https://user-images.githubusercontent.com/28706452/28620275-8048e968-720c-11e7-8d44-1486c038043f.png)

**Comment by jochenbuehler** [comment]
Here is more :)
![2017_07_26_14_14_41_kabel_oder_freileitung_korr pdf_adobe_acrobat_reader_dc](https://user-images.githubusercontent.com/28706452/28620357-e1e647ce-720c-11e7-8f7f-42ceb44ab493.png)

(soure: http://www.nlt.de/pics/medien/1_1191828963/Kabel_oder_Freileitung_korr.pdf)

**Comment by mltja** [comment]
Mentioned in #212 for information
