### ISSUE TITLE
Peak generation at LVLoadAreaDing0 vs. sum of peak generation in LV grids

### ISSUE THREAD

**Issue by gplssm** [openego/ding0#217]
We can compute the cumulative generation capacity in load areas by three ways 
1. by asking `LVLoadAreaDing0.peak_generation` (_gen_capacity_lv_la_)
2. by cumulating LV generators generation capacity in the underlying LV grid districts (_gen_capacity_lv_)
3. by using aggregated generation capacity at the LV station (_gen_capacity_lv_station_)

This looks like

```
gen_capacity_lv = 0
gen_capacity_lv_station = 0

for la in nd._mv_grid_districts[0]._lv_load_areas:
    gen_capacity_lv_la = la.peak_generation
    for lvgd in la._lv_grid_districts:
        grid = lvgd.lv_grid
        gen_capacity_lv_station = grid.station().peak_generation
        for gen in grid.generators():
            gen_capacity_lv += gen.capacity
```
Thereof three different numbers result

gen_capacity_lv: 15473.82
gen_capacity_lv_station: 154.78
gen_capacity_lv_la: 1089.37

Find out what causes the differences!

**Comment by nesnoj** [comment]
Everything is fine, your code lacks some `+`s.
Using
```
gen_capacity_lv = 0
gen_capacity_lv_station = 0
gen_capacity_lv_la = 0

for la in self._mv_grid_districts[0]._lv_load_areas:
    gen_capacity_lv_la += la.peak_generation
    for lvgd in la._lv_grid_districts:
        grid = lvgd.lv_grid
        gen_capacity_lv_station += grid.station().peak_generation
        for gen in grid.generators():
            gen_capacity_lv += gen.capacity
```
the generation cap. is 15473.82 kW in either case.
