### ISSUE TITLE
Correct MV transformer parameters

### ISSUE THREAD

**Issue by gplssm** [openego/ding0#223]
Parameters of MV transformers are in incorrect unit (s_nom) respectively are missing (x,r). 3 TODOs

- [x] Provide s in kVA
- [ ] Add r to type
- [ ] Add x to type
- [ ] Afterwards: edit PyPSA interface in eDisGo accordingly, see [eDisGo issue](https://github.com/openego/eDisGo/issues/19)

**Comment by nesnoj** [comment]
A good source is pandapower, see its [doc](https://pandapower.readthedocs.io/en/v1.4.0/std_types/basic.html#three-winding-transformers). (pyPSA is also [using](https://www.pypsa.org/doc/components.html#transformer-types) it).
But I cannot find r and x values, I guess they cannot be calculated from the given params? @jochenbuehler

**Comment by gplssm** [comment]
I already discussed about transformer parameters on the PyPSA mailing list. In [the discussion thread](https://groups.google.com/forum/#!topic/pypsa/6L3N6kNH2VY) you find the formula to calculate R and X

**Comment by nesnoj** [comment]
@jochenbuehler Please check your inbox.
The pyPSA/pp types got different nominal ratings and they list only 3 types.
One more thing: They have different types for 10 and 20kV (with significant differences in R and X for the same voltage!).
@jochenbuehler Should we replace our types and account for voltage?

**Comment by mltja** [comment]
Seems obsolete or fixed reopen if needed.
