### ISSUE TITLE
upload grid data to zenodo

### ISSUE THREAD

**Issue by nesnoj** [openego/ding0#227]
Please upload current (paper) dataset to zenodo as soon as possible. Thx!

**Comment by gplssm** [comment]
I started the upload. Should finish tonight...

**Comment by gplssm** [comment]
Upload is finish but publishing fails on 'internal server error'... :-1:

**Comment by gplssm** [comment]
Upload completed!

Cite version ding0_data_v0.1.2_170724.tar.gz: https://zenodo.org/record/856442

Cite all versions: https://doi.org/10.5281/zenodo.795210
