### ISSUE TITLE
package renaming

### ISSUE THREAD

**Issue by nesnoj** [openego/ding0#230]
Change package name to "egodingo" (available on pypi). Ok, @gplssm? Other suggestions?

**Comment by gplssm** [comment]
Nope :)

I suggest eDingo (available on pypi.python.org). Further I would like to merge the documentation branch prior to another renaming.

**Comment by nesnoj** [comment]
Uhh, this must be senile dementia. Right, we favoured "eDingo".

**Comment by gplssm** [comment]
Maybe pre-senile ;-)

**Comment by boltbeard** [comment]
Is there some sort of naming scheme  or convention that must be upheld? 
I'd like to suggest "Network Topology Estimator" - "NeToEs" or
 "Distribution Network Topology Estimator" - "DiNeToEs" both are available on pypi.

**Comment by nesnoj** [comment]
I'd have preferred a name that is similar to ding0, but as eGo is done by now and dependencies etc. are set, I'd avoid renaming. Therefore, I close this one..
