### ISSUE TITLE
Change LV grid load: Split retail/industrial into individual loads

### ISSUE THREAD

**Issue by gplssm** [openego/ding0#237]
In its current state, ding0 represents LV loads of the sectors industrial and retail as mixed loads "retail/industrial". For these sectors, the [cumulative peak load of both sectors is used to define the LV grid layout](https://github.com/openego/ding0/blob/dev/ding0/grid/lv_grid/build_grid.py#L204-#L211).
A load object that results of this [gets consumption of both sectors](https://github.com/openego/ding0/blob/dev/ding0/grid/lv_grid/build_grid.py#L258-#L267) assigned.

**Comment by gplssm** [comment]
The changes seemed plausible, but with the changes the reinforcement costs significantly change. [Further reading in the corresponding eDisGo issues #37](https://github.com/openego/eDisGo/issues/37). 

The branch `fix/#237-split-lv-sectors-retail-industrial` contains the related code.

**Comment by mltja** [comment]
Through major refactoring in the lv generation and changing of the data this issue is obsolete.
