### ISSUE TITLE
ding0 csv/oedb exporter geometry modifications

### ISSUE THREAD

**Issue by boltbeard** [openego/ding0#263]
- [ ] The geometry of LV Load areas is the from csv is the centre point of the load area which is what comes up in aggregated generators and load, in pickle files this is the connected node's point, this has to be fixed by the ding0 csv export
- [x] Include the LineString geometries of lines in export if lines.

 this is with specific reference to #256

**Comment by mltja** [comment]
Fixed or obsolete with new lv grid method.
