### ISSUE TITLE
Update description table

### ISSUE THREAD

**Issue by gplssm** [openego/ding0#269]
The exported CSV/OEDB tables are described in ding0's documentation. [These tables](https://github.com/openego/ding0/blob/5f913f22d54bce1c3267558d23d4b7fe72eee2f3/doc/usage_details.rst)  need to be updated according to the changes that were made to the CSV exporter. 

This encompasses all columns. Please use the [scripts that create the CSV tables](https://github.com/openego/ding0/blob/5f913f22d54bce1c3267558d23d4b7fe72eee2f3/ding0/tools/results.py#L2302-#L2513) as a reference for information.

**Comment by mltja** [comment]
Closed due to age, reopen if needed.
