### ISSUE TITLE
Add metadata to OEDB tables that store the ding0 grid data

### ISSUE THREAD

**Issue by gplssm** [openego/ding0#270]
First discussion about meta data lead to this [spreadsheet](https://docs.google.com/spreadsheets/d/1gSQ_H6zKo640TK705NeWBRRKsJkgKpcwdtk0g9AXX-w/edit#gid=1321404571) that should be used to kick-start with meta data creation.

Based on #268 and #269 there should enough information to start with creating meta data for the ding0 results tables in the OEDB.

**Comment by mltja** [comment]
Close due to age, reopen if needed.
