### ISSUE TITLE
release v0.1.9

### ISSUE THREAD

**Issue by nesnoj** [openego/ding0#273]
We need a final eGo release.

ToDos:
- [x] remove upper version bound of matplotlib dependency, test with recent version @nesnoj 
- [x] fix example script `example_analyze_single_grid_district.py` @nesnoj 
- [x] update docs: introduce oedialect @nesnoj 
- [ ] merge PRs #264 and #271 - i this really needed? @boltbeard 
- [ ] fix: LV voltage in kV in some grids @nesnoj 
- [x] merge features/fix_docs that fixed API doc at rtd @birgits and check if everything still works as some imports changed (@nesnoj @boltbeard I need to know what to check)

Please amend if necessary.

@birgits Is it ok for you to have it done by Oct 29th?
https://github.com/openego/eGo/issues/141 states Oct 22nd/23rd but I'll be on vacation next week.

**Comment by birgits** [comment]
@nesnoj Oct 29th is far too late as edisgo and ego depend on the ding0 release and releasing everything one day before the workshop seems too risky...

**Comment by boltbeard** [comment]
>  merge PRs #264 and #271 - i this really needed? @boltbeard 
I would say #271 is stable and is very critical to have for any use-case of ding0 that assumes non-unitity power factor on anything (load or generation)

#264 is still not stable, it is still in the "Work in Progress" state, and I would not recommend merging it in its current state

**Comment by nesnoj** [comment]
@birgits: Damn, I see my vacation to vanish.. :( I'll try to do this next week.
@boltbeard: I'll exclude those 2 PRs from the release

**Comment by boltbeard** [comment]
@nesnoj, you mean 1 PR?

**Comment by birgits** [comment]
@nesnoj how about you do point 1 of the list, @boltbeard does point 2 and merge of PR271, I do point 4 with help of @boltbeard and we drop points 3 and 5 for now? Point 1 should be fixed quite quick I guess. I would probably not use latest matplotlib version but the one suggested in networkx 1.11, which is 2.0.2.

**Comment by nesnoj** [comment]
No. 1 is done

**Comment by birgits** [comment]
Release is through! Thanks for your help!
