### ISSUE TITLE
Use geodesic distance calculations instead of vincenty from geopy

### ISSUE THREAD

**Issue by boltbeard** [openego/ding0#292]
The geographic distances in the functions are calculated using the vincenty algorithm in the pacakge geopy:
- [calc_geo_dist_vincenty](https://github.com/openego/ding0/blob/dev/ding0/tools/geo.py#L119-L152)
- [calc_geo_dist_matrix_vincenty](https://github.com/openego/ding0/blob/dev/ding0/tools/geo.py#L155-L203)
- [calc_geo_centre_point](https://github.com/openego/ding0/blob/dev/ding0/tools/geo.py#L206-L241)

Geopy in their [documentation](https://geopy.readthedocs.io/en/stable/#module-geopy.distance) have in the recent past changed its default distance calculation to geodesic as it is better (converges always) 

It would be prudent for us to use the same methods. It may also be good to use distance.distance instead of distance.vincenty

**Comment by nesnoj** [comment]
Concerning the accuracy (high enough) or non-convergence (the grid extends will hardly exceed 20000 km ;) I do not see a reason to change the method. But as vincenty [will be removed](https://geopy.readthedocs.io/en/stable/changelog_1xx.html#id7) in geopy v2.0, I agree!
Go for it

**Comment by nesnoj** [comment]
Done as part of #325
