### ISSUE TITLE
LV reinforce grid 

### ISSUE THREAD

**Issue by santiagoinfantinom** [openego/ding0#293]
The function reinforce grid in LVGridDing0 tries, when calculating critical voltages on the graph's nodes (specifically on the LVStation), to compute the MV impedance from a non existing connection between the LVStation and MVStation,which belong apparently to different graphs. Inside the function get_mv_impedance the function find_path throws an error while trying to solve the shortest path between those nodes.
Apparently the Grid is trying to be reinforced "From the bottom up" (i.e from the LV to the MV side) instead of creating further cables from the HV to the MV side in order to avoid critical voltages on the LV side.

**Comment by birgits** [comment]
We decided to move the reinforce_grid test to the MV tests. @santiagoinfantinom will do that using an already existing LV grid fixture and appending that LV grid to the MV test grid.
The other question is if we should change the order that the grid is reinforced from MV first and LV second (what does the guideline require?). @AnyaHe will have a look at that.

**Comment by santiagoinfantinom** [comment]
When looking at the function reinforce_grid in the MVGridDing0 section, I realized the function did only a reinforcement on the critical branches and not on the critical stations with the claim that the HV-MV transformers where chosen in a way that this would be avoided.

After seeing that, I decided to further look at the reinforce_grid function in the LVGridDing0 section to verify the assertion . There, the function requires a graph connection between the MV- and LVGrid to find the shortest path. Looking for a workaround I found out that this feature (connecting MV- and LV graphs) was indeed marked as a # TODO in the MVGridDing0 class and it's in my viewpoint needed to reinforce the MV-LV critical stations. 

Should this integration between MV and LV graphs be done in order to test the reinforcement function? Or is there another way to overcome this issue?

**Comment by AnyaHe** [comment]
Can you provide the code, where you found that a graph connection is necessary to find the shortest path? 
In my understanding the path is devided into mv and lv sections and the impedances are summed up in the end. This way you don't necessarily need the connected grids. And the reinforcement of stations could be done without the connection as only lv generators and loads are checked. Or am I missing something? Why do you think the link is necessary in this case?

**Comment by santiagoinfantinom** [comment]
The issue is now solved. It was a misunderstanding.
As the HV-MV Stations are reinforced in the MVGridDing0 section and its transformers were chosen to fit the voltages needed,  it made more sense to test the function in for the MV-LV Stations which is found in LVGridDing0. A small additional test will be pushed soon testing the reinforcement of critical stations and branches in the LVGrid.

**Comment by gplssm** [comment]
@santiagoinfantinom Is this issue resolved by PR #305 ? If so, please close
