### ISSUE TITLE
Test grid for validation of VDE AR 4105

### ISSUE THREAD

**Issue by AnyaHe** [openego/ding0#304]
It would be nice to implement the simple test grid that is used in VDE AR 4105 E.1 (p. 66) in order to check the functionality of function get_critical_voltage_at_node. 
A grid with the given mv impedance (maybe one line with hardcoded r and x is sufficient), transformer, lv lines and PV generators has to be created.

**Comment by AnyaHe** [comment]
<img width="549" alt="2019-08-21 16_35_39-AR 4105 VDE pdf - Adobe Acrobat Reader DC" src="https://user-images.githubusercontent.com/50416149/63441502-cdff1a00-c431-11e9-977e-f22c0157413f.png">

**Comment by mltja** [comment]
Close and consider in #377
