### ISSUE TITLE
Circuit breaker at station

### ISSUE THREAD

**Issue by AnyaHe** [openego/ding0#317]
So far circuit breakers are relocated in eDisGo and added to the stations, as this is where they are located in reality. Related to PR #312 and [eDisGo PR #159](https://github.com/openego/eDisGo/pull/159).
Todo:

[ ] move code that relocates circuit breaker to ding0

**Comment by nesnoj** [comment]
You've solved this in 2282b3125cc2ae01d2422b63e148b6c176675230, right @AnyaHe ?

**Comment by nesnoj** [comment]
:+1:
