### ISSUE TITLE
Question: Clarification LV_aggregated in network_nodes.csv

### ISSUE THREAD

**Issue by serpoten** [openego/ding0#337]
Hello,

I am struggling to understand what is the meaning of the `LV station (aggregated)` in the column `types` that appears in some of the networks created. I am getting this information from the `network_nodes.csv` file.

As far as I understood the code, it means that those nodes where `LV station (aggregated)` is given as a type, they do not count. I other words they are dummy data, because the network might not be properly created?

Am I wrong or correct in the assumption?

**Comment by mltja** [comment]
Closed due to the age and changed lv grids.
