### ISSUE TITLE
Unnecessary extra buses and lines in lv grids

### ISSUE THREAD

**Issue by khelfen** [openego/ding0#359]
Residential loads and generators are now connected to the same bus within lv grids, but there seems to be extra buses and lines downstream from loads without any function.

See this example lv grid with all loads marked bigger:
![Figure_2](https://user-images.githubusercontent.com/46815982/134504965-3cd2d382-f655-4880-a09c-815165f1d82c.png)

and this example with all generators marked bigger:
![Figure_1](https://user-images.githubusercontent.com/46815982/134505018-fdb76021-a797-42eb-945b-04fea30ad446.png)

Downstream of each load there is another bus with nothing connected but the line from the load. See this example:
![Screenshot at 2021-09-23 13-52-28](https://user-images.githubusercontent.com/46815982/134505224-c1caa587-31b8-4558-8b11-4247de130e8b.png)

**Comment by nesnoj** [comment]
Thanks for reporting, I think @AnyaHe modified the connection of residential loads and feeders, maybe she can help?

Is it crucial for your current work? I'm asking since the LV model grids will be replaced anyway by road-routed grids in the next months.

**Comment by khelfen** [comment]
It's not crucial :)

**Comment by mltja** [comment]
Solved in new_dev, reopen if still exists with new grids.
