### ISSUE TITLE
Rename peak_load in CSV export

### ISSUE THREAD

**Issue by nesnoj** [openego/ding0#365]
Replace `peak_load` by `p_nom` to be compatible with eDisGo.

**Comment by birgits** [comment]
In the course of that it would also be helpful if you added a column 'type' to the loads dataframe where you set the type to 'conventional_load'.

**Comment by birgits** [comment]
And please wait with this a bit until we decide whether to call it p_nom or p_set.

**Comment by khelfen** [comment]
In eDisGo we will call it `p_set`. Please do so in ding0 as well :)

**Comment by birgits** [comment]
Another helpful addition to the loads dataframe is the building ID the load is associated with. Please add that as well.

**Comment by mltja** [comment]
Implemented
