### ISSUE TITLE
read crs from db tables

### ISSUE THREAD

**Issue by nesnoj** [openego/ding0#62]
There are 2 CRS (WGS83 and ETRS89) used in the database. In DINGO, we store all geo_data in WGS84. To be safe using the right projection, we have to read the CRS and reproject to WGS84 prior to storing in attribute if necessary.

**Caution - stumbling block:** Reprojections need computing time, so handle with care! :)

**Comment by nesnoj** [comment]
Since we just stumbled across this problem again (compare old #5), this issue is still ongoing..

**Comment by gplssm** [comment]
If you want me to do something, please provide more detail information and is best-case a todo list ;-)

**Comment by piaulous** [comment]
closed, mentioned in https://github.com/openego/ding0/issues/385 fyi
