### ISSUE TITLE
implement testing for dingo

### ISSUE THREAD

**Issue by nesnoj** [openego/ding0#86]
According to project-wide planning, a software testing has to be implemented. See repo [example_code](https://github.com/openego/example_code/blob/master/example_code.py).

**Comment by boltbeard** [comment]
Currently a basic level of unittesting with pytests is under review in #277 but this branch needs to be futher populated with more unit-tests to improve the coverage of the code.
The recognized Todos to improve this are:

- [ ] Change the test for `MVGridDing0.routing()` to use the [prototype](https://gist.github.com/boltbeard/232cc6de188ad621988f6a3b4c952ae5) for this. The prototype checks individual node connections and edge attributes exahaustively (this is a more thorough test). The existing test function currently uses an example and checks if the `networkx.Graph` has the appropriate number of nodes, edges and the dimensions of the graph itself (centrality, diameter). 

- [ ] Add a Testcase to use the [example grid](https://github.com/openego/ding0/blob/dev/ding0/examples/example_single_grid_district.py) in conjuntion with the exising [example_analyze](https://github.com/openego/ding0/blob/dev/ding0/examples/example_analyze_single_grid_district.py) for the testing of ding0 overall.
